import {StyleSheet, Dimensions} from 'react-native';
import colors from './colors';
export const initialLayout = {
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height,
};
const CommonStyles = StyleSheet.create({
  keyboardAwareScroll: {
    display: 'flex',
    flex: 1,
    justifyContent: 'space-evenly',
    height: initialLayout.height,
    width: initialLayout.width,
  },
  safeAreaView: {
    flex: 1,
  },
  pageContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnSM: {
    width: 99,
    height: 26,
    borderRadius: 6,
    backgroundColor: colors.buttonBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnLG: {
    width: initialLayout.width * 0.8,
    height: 54,
    borderRadius: 6,
    alignSelf: 'center',
    backgroundColor: colors.buttonBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnLGOL: {
    width: 350,
    height: 44,
    borderRadius: 27,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: colors.color23,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnSMTxt: {
    color: '#fff',
    fontWeight: '400',
    fontSize: 12,
    textTransform: 'capitalize',
  },
  btnTxt: {
    color: '#fff',
    fontSize: 16,
    textTransform: 'uppercase',
    fontFamily: 'Signika',
  },
  btnTxtOl: {
    color: colors.color23,
    fontWeight: '600',
    fontSize: 16,
  },
  inputCont: {
    width: 350,
    height: 44,
    borderRadius: 6,
    alignSelf: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '400',
    fontStyle: 'normal',
    color: colors.color000,
    // lineHeight: 40,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '500',
    fontStyle: 'normal',
    color: colors.color23,
  },
  detailsTitle: {
    fontSize: 23,
    fontWeight: '500',
    fontStyle: 'normal',
    color: colors.color23,
  },
  detailsLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    fontStyle: 'normal',
    color: colors.color23,
    paddingVertical: 8,
  },
  detailsPara: {
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    color: colors.color000,
    paddingVertical: 8,
  },
  heading: {
    fontSize: 24,
    fontWeight: '600',
    fontStyle: 'normal',
    color: colors.colorFC0,
    lineHeight: 40,
    fontFamily: 'Livvic',
  },
  subHeading: {
    fontSize: 18,
    fontWeight: '400',
    fontStyle: 'normal',
    color: colors.color70,
    lineHeight: 20,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '400',
    fontStyle: 'normal',
    color: colors.color70,
    lineHeight: 16,
    fontFamily: 'Livvic',
  },
  forgotLabel: {
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    color: colors.colorF72,
    lineHeight: 16,
  },
  inputContainer: {
    height: 44,
    width: initialLayout.width * 0.9, // 350,
    borderRadius: 5,
    backgroundColor: colors.colorFFF,
    paddingHorizontal: 6,
    fontSize: 18,
    fontFamily: 'Livvic',
    color: colors.color000,
    borderWidth: 1,
    borderColor: colors.colorECE,
    elevation: 2,
  },
  backBtnCnt: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.color23,
    borderRadius: 12,
  },
  // Login/Register Page Or sign in with
  divider: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  hr: {
    height: 0.55,
    flex: 1,
    backgroundColor: colors.color70,
  },
  dividerL: {
    color: colors.color70,
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Livvic',
  },
});
export default CommonStyles;
